version: '3.4'

services:
  rstudiopreview:
    build:
      context: ./rstudio_docker
    container_name: rstudiopreview
    volumes:
      - /home/eric/r_dev_projects:/home/eric/r_dev_projects
      - /home/eric/.ssh:/home/eric/.ssh
      - /opt/local/renv/cache:/renv/cache
      - /home/eric/r_dev_projects/rstudio_config_dir:/home/eric/.config/rstudio
    restart:
      unless-stopped
    ports:
      - 8686:8787
    env_file: ./rstudio_docker/rstudio.env

